spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: Hi! I am loan Service In QA
  contactDetails:
    name: "Bibek"
    email: "qabibek@gmail.com"
  onCallSupport:
    -(555) 555-1234