spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: Hi! I am Accounts Service In Prod
  contactDetails:
    name: "Bibek"
    email: "livebibek@gmail.com"
  onCallSupport:
    -(555) 555-1234